#!/bin/sh

LOCAL=1
PEER=94

DEV=ipip0
# Real network to remote
NET_PREFIX=192.168.122
# Configured network on new interface
LOCAL_PREFIX=10.129.1

LOCAL_END=$NET_PREFIX.$LOCAL
PEER_END=$NET_PREFIX.$PEER
LOCAL_IP=$LOCAL_PREFIX.$LOCAL
PEER_IP=$LOCAL_PREFIX.$PEER


if [ "$1" = down ]; then
	ip link delete $DEV
else
	ip link add $DEV type ipip remote $PEER_END local $LOCAL_END
	ip address add $LOCAL_IP peer $PEER_IP dev $DEV
	ip link set $DEV up
fi
