#!/bin/sh
#
# 

IP=10.129.0.26/24
DEV1=veth1
DEV2=dummy0
MASTER=virbr0

if [ "$1" = down ]; then
	ip link delete $DEV1
else
	ip link add $DEV1 type veth peer name $DEV2
	ip link set $DEV1 master $MASTER
	ip address add $IP dev $DEV2
	ip link set $DEV1 up
fi

